const buildContentTypeTranslations = (
  uid: string,
  labels: Record<string, string>
) =>
  Object.fromEntries(
    Object.entries(labels).map(([fieldName, label]) => [
      `content-manager.content-types.${uid}.${fieldName}`,
      label,
    ])
  );

const ruTranslations = {
  ...buildContentTypeTranslations('api::application.application', {
    name: 'Имя',
    phone: 'Телефон',
    message: 'Сообщение',
    status: 'Статус заявки',
    source: 'Источник',
    consentGiven: 'Согласие на обработку персональных данных',
    consentAt: 'Дата и время согласия',
  }),
  ...buildContentTypeTranslations('api::contact-info.contact-info', {
    mainPhone: 'Основной телефон',
    secondPhone: 'Дополнительный телефон',
    mainEmail: 'Основной email',
    mainTelegramLink: 'Основная ссылка Telegram',
    secondTelegramLink: 'Дополнительная ссылка Telegram',
    maxMessengerLink: 'Ссылка MAX',
  }),
  ...buildContentTypeTranslations('api::license-info.license-info', {
    title: 'Название лицензии',
    number: 'Номер лицензии',
    date: 'Дата лицензии',
    imageUrls: 'Старые пути изображений лицензии',
    images: 'Изображения лицензии',
  }),
  ...buildContentTypeTranslations('api::privacy-policy.privacy-policy', {
    pageTitle: 'Заголовок страницы',
    lead: 'Вступительный текст',
    operatorTitle: 'Заголовок блока "Оператор"',
    operatorText: 'Текст блока "Оператор"',
    dataTitle: 'Заголовок блока "Какие данные обрабатываются"',
    dataItems: 'Список обрабатываемых данных',
    purposesTitle: 'Заголовок блока "Цели обработки"',
    purposesItems: 'Список целей обработки',
    legalBasisTitle: 'Заголовок блока "Правовые основания"',
    legalBasisText: 'Текст блока "Правовые основания"',
    actionsTitle: 'Заголовок блока "Действия с данными"',
    actionsText: 'Текст блока "Действия с данными"',
    storageTitle: 'Заголовок блока "Срок хранения"',
    storageText: 'Текст блока "Срок хранения"',
    rightsTitle: 'Заголовок блока "Права субъекта"',
    rightsText: 'Текст блока "Права субъекта"',
    securityTitle: 'Заголовок блока "Защита данных"',
    securityText: 'Текст блока "Защита данных"',
    finalTitle: 'Заголовок блока "Заключительные положения"',
    finalText: 'Текст блока "Заключительные положения"',
  }),
  ...buildContentTypeTranslations('api::requisites.requisites', {
    ogrn: 'ОГРН',
    ogrnDate: 'Дата ОГРН',
    inn: 'ИНН',
    kpp: 'КПП',
    registrationDate: 'Дата регистрации',
    legalAddress: 'Юридический адрес',
    actualAddresses: 'Фактические адреса',
    head: 'Руководитель',
    mainActivity: 'Основной вид деятельности',
    taxAuthority: 'Налоговый орган',
    okpo: 'ОКПО',
    okato: 'ОКАТО',
    oktmo: 'ОКТМО',
    okfs: 'ОКФС',
    okogu: 'ОКОГУ',
    okopf: 'ОКОПФ',
  }),
  ...buildContentTypeTranslations('api::service.service', {
    title: 'Название услуги',
    description: 'Описание услуги',
    icon: 'Иконка',
    order: 'Порядок сортировки',
  }),
  ...buildContentTypeTranslations('api::site-content.site-content', {
    homeHeroTitle: 'Главная: заголовок hero',
    homeHeroDescription: 'Главная: описание hero',
    homeHeroImage: 'Главная: фото hero',
    socialGoalTitle: 'Главная: заголовок блока "Наша цель"',
    socialGoalText: 'Главная: текст блока "Наша цель"',
    motivationalBannerTitle: 'Главная: заголовок мотивационного баннера',
    motivationalBannerDescription: 'Главная: текст мотивационного баннера',
    aboutHeroTitle: 'О нас: заголовок hero',
    aboutHeroSubtitle: 'О нас: подзаголовок hero',
    aboutHeroDescription: 'О нас: описание hero',
    aboutHeroButtonText: 'О нас: текст кнопки hero',
    teamTitle: 'О нас: заголовок блока команды',
    teamDescription: 'О нас: описание блока команды',
  }),
  ...buildContentTypeTranslations('api::step.step', {
    title: 'Заголовок шага',
    description: 'Описание шага',
    order: 'Порядок сортировки',
  }),
  ...buildContentTypeTranslations('api::story.story', {
    description: 'Описание истории',
    image: 'Изображение',
    order: 'Порядок сортировки',
  }),
  ...buildContentTypeTranslations('api::ui-content.ui-content', {
    navAboutUsLabel: 'Меню: О нас',
    navRequisitesLabel: 'Меню: Реквизиты',
    navPrivacyPolicyLabel: 'Меню: Политика персональных данных',
    headerNavAriaLabel: 'Header: aria-метка навигации',
    headerEmailLinkTitle: 'Header: title ссылки email',
    burgerMenuOpenLabel: 'Header: aria-текст "открыть меню"',
    burgerMenuCloseLabel: 'Header: aria-текст "закрыть меню"',
    logoText: 'Header: текст логотипа',
    logoAriaLabel: 'Header: aria-метка логотипа',
    logoAlt: 'Header: alt логотипа',
    skipLinkText: 'Служебная ссылка "Перейти к содержимому"',
    phoneLinkLabelPrefix: 'Header: префикс aria-текста телефона',
    footerCopyrightText: 'Footer: копирайт',
    footerPrivacyPolicyText: 'Footer: ссылка на политику',
    contactFormTitlePrefix: 'Форма: первая строка заголовка',
    contactFormTitleMiddle: 'Форма: слово перед выделением',
    contactFormTitleHighlight: 'Форма: выделенный текст заголовка',
    contactFormTitleSuffix: 'Форма: последняя строка заголовка',
    contactFormWorkingHoursText: 'Форма: время работы',
    contactFormNameLabel: 'Форма: label имени',
    contactFormPhoneLabel: 'Форма: label телефона',
    contactFormMessageLabel: 'Форма: label сообщения',
    contactFormNamePlaceholder: 'Форма: placeholder имени',
    contactFormPhonePlaceholder: 'Форма: placeholder телефона',
    contactFormMessagePlaceholder: 'Форма: placeholder сообщения',
    contactFormConsentPrefix: 'Форма: текст согласия до ссылки',
    contactFormConsentLinkText: 'Форма: текст ссылки на политику',
    contactFormConsentSuffix: 'Форма: текст согласия после ссылки',
    contactFormSubmitButtonText: 'Форма: текст кнопки отправки',
    contactFormSubmittingButtonText: 'Форма: текст кнопки во время отправки',
    contactFormSubmittingSrText: 'Форма: скрытый текст для screen reader при отправке',
    contactFormNameRequiredError: 'Форма: ошибка "имя обязательно"',
    contactFormPhoneFormatError: 'Форма: ошибка формата телефона',
    contactFormMessageRequiredError: 'Форма: ошибка "сообщение обязательно"',
    contactFormConsentRequiredError: 'Форма: ошибка согласия',
    contactFormSendSuccessText: 'Форма: сообщение об успешной отправке',
    contactFormSendFailureText: 'Форма: сообщение об ошибке отправки',
    homeHeroMaxButtonText: 'Главная hero: кнопка MAX',
    homeHeroTelegramButtonText: 'Главная hero: кнопка Telegram',
    homeHeroCallButtonText: 'Главная hero: кнопка звонка',
    sliderPrevSlideMessage: 'Слайдер: aria-текст "предыдущий слайд"',
    sliderNextSlideMessage: 'Слайдер: aria-текст "следующий слайд"',
    homeServicesTitle: 'Главная: заголовок блока услуг',
    homeServicesFootnote: 'Главная: сноска под услугами',
    homeMotivationalCallButtonText: 'Главная: кнопка мотивационного баннера',
    aboutHowWeWorkTitle: 'О нас: заголовок "Как мы работаем"',
    aboutValuesTitle: 'О нас: заголовок "Наши ценности"',
    resultsPageTitle: 'Результаты: заголовок страницы',
    resultsStoryAltPrefix: 'Результаты: префикс alt для истории',
    requisitesPageTitle: 'Реквизиты: заголовок страницы',
    requisitesTableCaption: 'Реквизиты: подпись таблицы',
    requisitesColumnNameLabel: 'Реквизиты: колонка "Наименование"',
    requisitesColumnValueLabel: 'Реквизиты: колонка "Значение"',
    requisitesOgrnLabel: 'Реквизиты: label ОГРН',
    requisitesOgrnDatePrefix: 'Реквизиты: префикс даты ОГРН',
    requisitesInnKppLabel: 'Реквизиты: label ИНН/КПП',
    requisitesRegistrationDateLabel: 'Реквизиты: label даты регистрации',
    requisitesLegalAddressLabel: 'Реквизиты: label юридического адреса',
    requisitesActualAddressLabel: 'Реквизиты: label фактического адреса',
    requisitesHeadLabel: 'Реквизиты: label руководителя',
    requisitesMainActivityLabel: 'Реквизиты: label основного вида деятельности',
    requisitesTaxAuthorityLabel: 'Реквизиты: label налогового органа',
    requisitesOkpoLabel: 'Реквизиты: label ОКПО',
    requisitesOkatoLabel: 'Реквизиты: label ОКАТО',
    requisitesOktmoLabel: 'Реквизиты: label ОКТМО',
    requisitesOkfsLabel: 'Реквизиты: label ОКФС',
    requisitesOkoguLabel: 'Реквизиты: label ОКОГУ',
    requisitesOkopfLabel: 'Реквизиты: label ОКОПФ',
    notFoundSubtitle: '404: подзаголовок',
    notFoundText: '404: текст',
    notFoundLinkText: '404: текст ссылки',
    notFoundLinkAriaLabel: '404: aria-метка ссылки',
    licenseImageAltPrefix: 'Лицензия: префикс alt изображения',
  }),
  ...buildContentTypeTranslations('api::value.value', {
    title: 'Заголовок ценности',
    description: 'Описание ценности',
    icon: 'Иконка',
    order: 'Порядок сортировки',
  }),
};

export default {
  config: {
    locales: ['ru'],
    translations: {
      ru: ruTranslations,
    },
  },
};
